# Generated by Django 3.1.3 on 2020-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20201130_1611'),
        ('departmants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='department_food', to='foods.FoodCategory', verbose_name='Кухня'),
        ),
    ]
