# Generated by Django 3.1.3 on 2020-11-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201130_1702'),
        ('departmants', '0002_auto_20201130_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='food',
        ),
        migrations.AddField(
            model_name='department',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_food', to='foods.foodcategory', verbose_name='Кухня'),
        ),
    ]
