# Generated by Django 3.1.3 on 2020-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201130_1702'),
        ('departmants', '0003_auto_20201130_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='food',
        ),
        migrations.AddField(
            model_name='department',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='department_food', to='foods.FoodCategory', verbose_name='Кухня'),
        ),
    ]
