# Generated by Django 3.1.3 on 2020-12-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201130_1702'),
        ('departmants', '0004_auto_20201130_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_food', to='foods.FoodCategory', verbose_name='Кухня'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='К скольки часам забронировать столик')),
                ('people', models.PositiveIntegerField(verbose_name='Число людей')),
                ('open', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmants.department', verbose_name='Место расположения')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmants.table', verbose_name='Стол')),
            ],
        ),
    ]
