# Generated by Django 3.1.3 on 2020-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201130_1702'),
        ('departmants', '0005_auto_20201201_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='department_food', to='foods.FoodCategory', verbose_name='Кухня'),
        ),
    ]
