# Generated by Django 3.1.3 on 2020-12-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmants', '0008_booking_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
