# Generated by Django 3.1.3 on 2020-12-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmants', '0010_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='departmants.department', verbose_name='Место расположения'),
        ),
    ]
